#!name=儿歌点点
#!desc=儿歌点点会员
#!homepage=https://github.com/deezertidal
#!author=ddgksf2013
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/egdd.png
[Script]
儿歌点点=type=http-response,pattern=http:\/\/gateway\.ergediandian\.com\/dduser\/user\/center\/set,requires-body=1,script-path=https://raw.githubusercontent.com/sanjicc/SRModule/main/script/egdd.js
[MITM]
hostname = %APPEND% *.ergediandian.com